source 'https://rubygems.org'

gem 'docile'
gem 'json'
gem 'rexml'
gem 'simplecov'
gem 'bashcov'
gem 'codecov'
gem 'simplecov-cobertura'
gem 'simplecov-csv'
gem 'simplecov_json_formatter'
gem 'simplecov-tailwindcss'

