#!/usr/bin/env bash

# Bundler Script
# Merges all source files into a single monolithic script for compilation.

OUTPUT="dist/cloudflare-dns-updater-monolith.sh"
mkdir -p dist

echo "Bundling to $OUTPUT..."

# 1. Shebang
echo '#!/bin/bash' >"$OUTPUT"
echo '# Monolith build generated by tools/bundle.sh' >>"$OUTPUT"

# 2. Add Source Modules (Order matters)
for file in src/logger.sh src/network.sh src/config.sh src/ip.sh src/cloudflare.sh src/notifications.sh; do
	echo "Adding $file..."
	echo -e "\n# --- Module: $file ---" >>"$OUTPUT"
	sed '/^#!/d; /^[[:space:]]*source /d; /^[[:space:]]*# shellcheck /d' "$file" >>"$OUTPUT"
done

# 3. Add Main Logic (src/main.sh)
echo "Adding src/main.sh..."
echo -e "\n# --- Module: src/main.sh ---" >>"$OUTPUT"
sed '/^#!/d; /^[[:space:]]*source /d; /^[[:space:]]*# shellcheck /d; /^[[:space:]]*DIR=/d; /^[[:space:]]*main \"\$@\"/d' src/main.sh >>"$OUTPUT"

# 4. Add Lock and Config Logic (Wrapper)
cat <<'EOF' >>"$OUTPUT"

# --- Wrapper Logic ---



# Resolve directory (Monolith is self-contained)



DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"



# For makeself bundles, we need the original launching directory



ORIGINAL_PWD="${MAKESELF_PWD:-$PWD}"







# Initialize defaults



export SILENT="false"



export DEBUG="false"



export FORCE="false"



CONFIG_FILE=""







# Parse Arguments



for arg in "$@"; do



	case $arg in



	-s | --silent)



		export SILENT="true"



		;;



	-d | --debug)



		export DEBUG="true"



		;;



	-f | --force)



		export FORCE="true"



		;;



	*)



		# Check if it's a file, either absolute or relative to ORIGINAL_PWD



		if [[ -f "$arg" ]] && [[ "$arg" == *.yaml ]]; then



			CONFIG_FILE="$arg"



		elif [[ -f "$ORIGINAL_PWD/$arg" ]] && [[ "$arg" == *.yaml ]]; then



			CONFIG_FILE="$ORIGINAL_PWD/$arg"



		fi



		;;



	esac



done







# Debug info



if [[ "$DEBUG" == "true" ]]; then



	echo "Debug: Bundle Directory (DIR): $DIR"



	echo "Debug: Original Directory (ORIGINAL_PWD): $ORIGINAL_PWD"



	echo "Debug: Config File (Resolved): $CONFIG_FILE"



fi







# Fallback config lookup



if [[ -z "$CONFIG_FILE" ]]; then



	if [[ -f "$ORIGINAL_PWD/cloudflare-dns.yaml" ]]; then



		CONFIG_FILE="$ORIGINAL_PWD/cloudflare-dns.yaml"



	elif [[ -f "$DIR/cloudflare-dns.yaml" ]]; then



		CONFIG_FILE="$DIR/cloudflare-dns.yaml"



	fi



fi



# --- LOCK MECHANISM ---

LOCKFILE="/tmp/cloudflare-dns-updater.lock"

if [[ ! -d "/tmp" ]]; then

	LOCKFILE="$DIR/cloudflare-dns-updater.lock"

fi



if [[ -f "$LOCKFILE" ]]; then

	PID=$(cat "$LOCKFILE")

	if ps -p "$PID" >/dev/null 2>&1; then

		echo "Script is already running (PID: $PID). Exiting."

		exit 1

	else

		echo "Found stale lock file (PID: $PID). Overwriting."

	fi

fi



echo $ >"$LOCKFILE"

trap 'rm -f "$LOCKFILE"' EXIT

# ----------------------



if [[ ! -f "$CONFIG_FILE" ]]; then

	echo "Error: Configuration file not found!"

	echo "Please provide a valid .yaml file as an argument or create 'cloudflare-dns.yaml' in the current directory."

	exit 1

fi



# Run Main

main "$CONFIG_FILE"

EOF

chmod +x "$OUTPUT"
echo "Done. Created $OUTPUT"
