#!/usr/bin/env bash

# Bundler Script
# Merges all source files into a single monolithic script for compilation.

OUTPUT="dist/cloudflare-dns-updater-monolith.sh"
mkdir -p dist

echo "Bundling to $OUTPUT..."

# 1. Shebang
echo '#!/bin/bash' > "$OUTPUT"
echo '# Monolith build generated by tools/bundle.sh' >> "$OUTPUT"

# 2. Add Source Modules (Order matters)
# We strip shebangs and source commands
for file in src/logger.sh src/config.sh src/ip.sh src/cloudflare.sh src/notifications.sh; do
    echo "Adding $file..."
    echo -e "\n# --- Module: $file ---" >> "$OUTPUT"
    # Read file, remove shebang, append
    sed '/^#!/d' "$file" >> "$OUTPUT"
done

# 3. Add Main Logic (src/main.sh)
# We need to strip the 'source' commands since we included them above
echo "Adding src/main.sh..."
echo -e "\n# --- Module: src/main.sh ---" >> "$OUTPUT"
sed '/^#!/d; /^source /d; /^# shellcheck source=/d' src/main.sh >> "$OUTPUT"

# 4. execution Wrapper Logic (from cloudflare-dns-updater.sh)
# We need the lock logic and the call to main.
# executing src/main.sh usually calls 'main "$@"' at the end.
# Let's check if src/main.sh calls 'main' at the end. Yes it does: 'main "$@"'
# But we want the wrapper logic (Lock) to run *before* main.

# Wait, src/main.sh calls 'main "$@"' at the very end.
# If we simply paste src/main.sh, it will execute main immediately upon sourcing/running.
# We want to inject the Lock logic BEFORE 'main "$@"' is called.
# Or, clearer: The wrapper `cloudflare-dns-updater.sh` sets up file locks and THEN calls main.

# Revised Strategy for Step 3 & 4:
# We will modify the appending of src/main.sh to REMOVE the 'main "$@"' call at the end.
# Then we append the Lock Logic.
# Then we manually call 'main "$CONFIG_FILE"'.

# Remove the last line of main.sh (assuming it is 'main "$@"')?
# Better: regex remove 'main "$@"'
sed -i '$d' "$OUTPUT" # Remove the last line (which likely calls main "$@")?
# Let's be safer. Reading main.sh content and filtering.

# Let's rewrite Step 3 to filter carefully.
# We need to extract the functions from main.sh but NOT the execution `main "$@"`.
sed '/^#!/d; /^source /d; /^# shellcheck source=/d; /^main "\$@"/d' src/main.sh >> "$OUTPUT"

# 5. Add Lock and Config Logic (Recreating the wrapper logic)
cat << 'EOF' >> "$OUTPUT"

# --- Wrapper Logic ---

# Resolve directory (Monolith is self-contained)
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
CONFIG_FILE="$DIR/cloudflare-dns.yaml"

# --- LOCK MECHANISM ---
LOCKFILE="/tmp/cloudflare-dns-updater.lock"
if [[ ! -d "/tmp" ]]; then
    LOCKFILE="$DIR/cloudflare-dns-updater.lock"
fi

if [[ -f "$LOCKFILE" ]]; then
    PID=$(cat "$LOCKFILE")
    if ps -p "$PID" > /dev/null 2>&1; then
        echo "Script is already running (PID: $PID). Exiting."
        exit 1
    else
        echo "Found stale lock file (PID: $PID). Overwriting."
    fi
fi

echo $$ > "$LOCKFILE"
trap 'rm -f "$LOCKFILE"' EXIT
# ----------------------

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Configuration file cloudflare-dns.yaml not found at $CONFIG_FILE"
    exit 1
fi

# Run Main
main "$CONFIG_FILE"

EOF

chmod +x "$OUTPUT"
echo "Done. Created $OUTPUT"
